# Generated by Django 5.1.3 on 2024-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('eventDuration', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='', unique=True)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
    ]
