# Generated by Django 5.1.3 on 2024-12-01 01:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
